apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: a4971fdc-3094-41bb-aae5-2b4dcd08010f
    keyvaultName: cikeyvaulttest
    objects: |
      array:
        - |
          objectName: grafana-admin-user
          objectType: secret
        - |
          objectName: grafana-admin-password
          objectType: secret
    tenantId: 5159fdaa-fc6b-46fc-a28e-8f6a27aa5862
  secretObjects:
  - data:
    - key: admin-user
      objectName: grafana-admin-user
    - key: admin-password
      objectName: grafana-admin-password
    secretName: grafana-admin-credentials
    type: Opaque
