apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: b903e95f-4024-4f64-850d-4763b41a44b7
    keyvaultName: cikeyvaulttest
    objects: |
      array:
        - |
          objectName: grafana-admin-user
          objectType: secret
        - |
          objectName: grafana-admin-password
          objectType: secret
    tenantId: 5159fdaa-fc6b-46fc-a28e-8f6a27aa5862
  secretObjects:
  - data:
    - key: admin-user
      objectName: grafana-admin-user
    - key: admin-password
      objectName: grafana-admin-password
    secretName: grafana-admin-credentials
    type: Opaque
