apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: fcd9988c-4437-4712-a3e8-1372b91ae01c # Client ID of the Workload Identity (Managed Identity), see $WORKLOAD_IDENTITY_NAME --> Dieser Wert muss aktuell manuell gepflegt werden, bis Terraform den Output automatisiert zur Verfügung stellt
    keyvaultName: ci-tfs-prod # Name of the key vault, see $KEYVAULT_NAME
    objects:  |
      array:
        - |
          objectName: grafana-admin-user
          objectType: secret
        - |
          objectName: grafana-admin-password
          objectType: secret
    tenantId: 5159fdaa-fc6b-46fc-a28e-8f6a27aa5862 # Tenant ID where the resources resides
  secretObjects:
  - data:
    - key: admin-user
      objectName: grafana-admin-user
    - key: admin-password
      objectName: grafana-admin-password
    secretName: grafana-admin-credentials
    type: Opaque