apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  sources:
  - repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 8.4.1
    helm:
        valueFiles:
        - $values/argocd/apps/nextcloud/values.yaml
  - repoURL: https://github.com/Comin-SH/aks.git
    targetRevision: main
    ref: values
  # - repoURL: 'https://github.com/Comin-SH/aks.git'
  #   path: argocd/apps/nextcloud
  #   targetRevision: main
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc